name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Unit tests passed
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        state: 'success'

    - name: Unit tests failed
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        state: 'failure'
